spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boca-de-urna
    username: user
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
#      ddl-auto: create